### ISSUE TITLE
superblock structure is missing one field

### ISSUE THREAD

**Issue by Agile86** [TheCodeArtist/ext2-parser#4]
The main structure is missing single field:
between state and minor_rev_level there are missing s_errors
```
os_uint16_t s_state;
os_uint16_t s_errors;   <------------------ MISSING
os_uint16_t s_minor_rev_level;
```

**Comment by TheCodeArtist** [comment]
Thanks @Agile86. I have added the missing field now.
Let me know if you find anything else the needs fixing.
